/**
 * Security Addendum content
 * This file contains all legal content for the Security page.
 * Edit the sections array to update the terms.
 */

import type {
  LegalSection,
  LegalPageMetadata,
} from "@/components/layouts/LegalPageLayout";

export const securityMetadata: LegalPageMetadata = {
  title: "Security Addendum",
  lastUpdated: "January 16, 2026",
  introduction:
    "This Security Addendum (“Security Addendum”) forms part of, and is subject to, the Overbase Terms of Service or other written agreement between Overbase and Customer (the “Agreement”). Capitalized terms not defined herein shall have the meanings set forth in the Agreement or the Data Processing Addendum (“DPA”).",
};

export const securitySections: LegalSection[] = [
  {
    id: "security-architecture",
    title: "Security Architecture",
    content: [],
    subsections: [
      {
        title: "1.1. Service Design",
        content: [
          'Overbase represents that the Service is designed as a "secure-by-design" automated question and answer system. The Service connects to Customer’s internal data sources (including structured sources, such as Salesforce, and unstructured sources, such as Gong) to process queries and generate answers.',
        ],
      },
      {
        title: "1.2. No Permanent Storage of Source Data",
        content: [
          "Overbase does not maintain permanent storage of Customer Data derived from Customer’s internal data sources. Customer Data remains resident within Customer’s existing platforms and tools. Overbase accesses such data solely on a transient basis as required to generate answers.",
        ],
      },
      {
        title: "1.3. Data Retention Periods",
        content: [
          "(a) Processing Data: Any Customer Data temporarily cached or stored during processing, including internal team communications regarding such data, is deleted within thirty (30) days of collection.",
          "(b) Generated Answers: Questions submitted by Users and the answers generated by the Service are stored to facilitate the User experience. By default, such questions and answers are deleted thirty (30) days after generation, unless Customer configures the Service to retain them for a longer period.",
        ],
      },
    ],
  },
  {
    id: "data-processing-ai",
    title: "Data Processing",
    content: [],
    subsections: [
      {
        title: "2.1. Self-Hosted Model Infrastructure",
        content: [
          "Overbase performs all data analysis using a self-hosted Large Language Model (LLM) deployed within Overbase’s private, secure infrastructure. This model is not accessed via third-party APIs or cloud-based interfaces, ensuring that all processing and training occur on hardware under Overbase's exclusive control.",
        ],
      },
      {
        title: "2.2. Customer-Owned Training & Deletion",
        content: [
          "Customer Data is utilized to train and optimize the AI model instance dedicated to the Customer. Overbase warrants that each trained model is the exclusive property of the Customer. Upon termination or expiration of the Agreement, Overbase shall permanently delete the dedicated model and all associated trained parameters.",
        ],
      },
      {
        title: "2.3. Human Review",
        content: [
          'Where Overbase personnel ("Reviewers") review analysis based on Customer Data to ensure quality, such work is performed exclusively within encrypted tools. All data history within these tools, including internal messenger history used for collaboration, is legally and technically mandated to be deleted every thirty (30) days.',
        ],
      },
    ],
  },
  {
    id: "credential-management",
    title: "Credential Management",
    content: [],
    subsections: [
      {
        title: "3.1. Physical Storage (Air-Gapping)",
        content: [
          'Credentials, API keys, passwords, and logins provided by Customer ("Credentials") are stored exclusively on physical hard drives located within a locked safe in Overbase’s secure facility. These hard drives are not connected to the internet while in storage and are accessed only when operationally necessary.',
        ],
      },
      {
        title: "3.2. Manual Injection of Credentials",
        content: [
          'Overbase maintains a strict "Human-in-the-Loop" protocol for system access. No Overbase automated system can access Customer systems without human intervention. A human operator must manually enter Customer Credentials each time the Service launches an agent requiring access to Customer systems.',
        ],
      },
      {
        title: "3.3. Credential Destruction",
        content: [
          "Upon disposal or replacement, physical hard drives containing Customer Credentials are physically destroyed.",
        ],
      },
    ],
  },
  {
    id: "operational-security",
    title: "Operational Security",
    content: [],
    subsections: [
      {
        title: "4.1. Restricted Personnel",
        content: [
          'With the exception of the Overbase CEO, all Overbase personnel with access to Customer Data or Credentials ("Secure Personnel") adhere to the protocols set forth in this Section 4.',
        ],
      },
      {
        title: '4.2. The "Walled Garden" Protocol',
        content: [
          "(a) No External Collaboration: Secure Personnel are prohibited from collaborating with external partners, customers, or third parties.",
          "(b) Communication Restrictions: Secure Personnel communicate and collaborate internally solely using encrypted services subject to the 30-day deletion policy described in Section 1.3. Secure Personnel are not issued Overbase email addresses and are not contactable by the public via corporate channels.",
          "(c) Service Restrictions: Secure Personnel are prohibited from registering for third-party services other than approved encrypted services that are provisioned, monitored, and audited by Overbase.",
        ],
      },
      {
        title: "4.3. Secure Facility and Hardware",
        content: [
          "(a) Location: Secure Personnel perform all duties in-person from a dedicated secure office facility monitored 24/7 by video surveillance.",
          "(b) Device Restriction: Secure Personnel utilize desktop computers that cannot be removed from the secure facility.",
          "(c) Mobile Device Ban: Personal electronic devices, including mobile phones, are strictly prohibited within the secure facility.",
        ],
      },
      {
        title: "4.4. Workstation Monitoring",
        content: [
          "Workstations utilized by Secure Personnel are equipped with monitoring software that records screen activity and logs keystrokes to ensure strict compliance with security protocols.",
        ],
      },
    ],
  },
  {
    id: "personnel-anonymity",
    title: "Personnel Confidentiality",
    content: [],
    subsections: [
      {
        title: "5.1. Social Media Restrictions",
        content: [
          "To reduce surface area for social engineering, Secure Personnel are incentivized (via compensation structure) to refrain from using, updating, or logging into social media accounts.",
        ],
      },
      {
        title: "5.2. Non-Disclosure Agreements (NDAs)",
        content: [
          "All Secure Personnel execute strict NDAs with Overbase prohibiting the disclosure of any Customer information.",
        ],
      },
      {
        title: "5.3. Violations",
        content: [
          "Any violation of the security protocols outlined in this Addendum by Secure Personnel, including minor infractions such as the introduction of a mobile device into the secure facility, results in immediate termination of employment.",
        ],
      },
    ],
  },
  {
    id: "user-compliance",
    title: "User Compliance",
    content: [],
    subsections: [
      {
        title: "6.1. Credential Sharing",
        content: [
          "Users are prohibited from sharing login credentials. Overbase monitors usage for concurrent access or anomalies indicative of credential sharing. Overbase reserves the right to immediately suspend or terminate User access for confirmed violations of this policy.",
        ],
      },
    ],
  },
  {
    id: "enterprise-tier",
    title: "Enterprise Tier Enhancements",
    content: [],
    subsections: [
      {
        title: "7.1. Applicability",
        content: [
          "The provisions of this Section 7 apply solely to Customers subscribed to the Enterprise Tier.",
        ],
      },
      {
        title: "7.2. Custom NDAs",
        content: [
          "Enterprise Tier Customers may elect to require Secure Personnel to execute direct, custom NDAs provided by the Customer.",
        ],
      },
      {
        title: "7.3. Enhanced Social Media Ban",
        content: [
          "Notwithstanding Section 5.1, Secure Personnel authorized to access Enterprise Tier Customer Data are strictly prohibited from using social media, ensuring they cannot be easily identified or contacted by third parties.",
        ],
      },
    ],
  },
];
